# Generated by Django 4.2.7 on 2023-12-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='horario32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='linhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('List_id_pontos', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('id_linha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='onibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.TimeField()),
                ('lotacao', models.IntegerField()),
                ('id_onibus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ponto', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('lotacao', models.IntegerField()),
                ('id_onibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busflow.onibus')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('is_adm', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('id_onibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busflow.onibus')),
                ('id_ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busflow.pontos')),
            ],
        ),
        migrations.AddField(
            model_name='onibus',
            name='id_last_ponto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busflow.pontos'),
        ),
        migrations.AddField(
            model_name='onibus',
            name='id_linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busflow.linhas'),
        ),
    ]
