# Generated by Django 4.2.7 on 2023-12-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos',
            name='id_onibus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busflow.onibus'),
        ),
    ]
