# Generated by Django 4.2.7 on 2023-12-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busflow', '0002_alter_pontos_id_onibus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linhas',
            name='id_linha',
        ),
        migrations.RemoveField(
            model_name='onibus',
            name='id_onibus',
        ),
        migrations.RemoveField(
            model_name='pontos',
            name='id_ponto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='onibus',
            name='id_last_ponto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busflow.pontos'),
        ),
        migrations.AlterField(
            model_name='onibus',
            name='lotacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pontos',
            name='lotacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_onibus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busflow.onibus'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_ponto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busflow.pontos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_adm',
            field=models.IntegerField(default=0),
        ),
    ]
