# Generated by Django 4.2.7 on 2023-12-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busflow', '0003_remove_linhas_id_linha_remove_onibus_id_onibus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onibus',
            name='last_time',
            field=models.TimeField(null=True),
        ),
    ]
